#!/usr/bin/env python
"""Render CoPaw's release-channel fact source for each consumer.

    python scripts/release_channel.py --print
    python scripts/release_channel.py --sh
    GITHUB_ENV=... python scripts/release_channel.py --gh-env
    python scripts/release_channel.py --write-ts [--out PATH]

``--sh`` serves a *checkout* of this repository; the shipped installers are
``curl … | bash`` and have neither a checkout nor Python, so they carry the
literals and the consistency gate keeps them equal to this file.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
FACT_SOURCE = REPO_ROOT / "src/copaw/release_channel.json"
LOADER_MODULE = REPO_ROOT / "src/copaw/release_channel.py"
GENERATED_TS = REPO_ROOT / "console/src/generated/releaseChannel.ts"

TS_HEADER = (
    "// GENERATED by scripts/release_channel.py --write-ts. "
    "Do not edit by hand.\n"
    "// Fact source: src/copaw/release_channel.json\n"
)
TS_FOOTER = (
    "\nexport const githubUrl = "
    "`https://github.com/${RELEASE_CHANNEL.github_repository}`;\n"
    "export const releasesUrl = `${githubUrl}/releases`;\n"
)

# env name suffix -> fact-source key; a tuple means a nested (assets) lookup.
ENV_FIELDS = (
    ("DISTRIBUTION", "distribution"),
    ("PYPI_PROJECT", "pypi_project"),
    ("UPSTREAM_VERSION", "upstream_version"),
    ("GITHUB_REPOSITORY", "github_repository"),
    ("DOCKER_NAMESPACE", "docker_namespace"),
    ("DOWNLOAD_CDN", "download_cdn"),
    ("ASSET_WINDOWS", ("assets", "windows")),
    ("ASSET_MACOS", ("assets", "macos")),
)


def _loader():
    spec = importlib.util.spec_from_file_location(
        "_copaw_release_channel", LOADER_MODULE
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _scalar(data: dict[str, Any], key: Any) -> Any:
    value: Any = data
    if isinstance(key, tuple):
        for part in key:
            value = value[part]
        return value
    return value[key]


def env_map(data: dict[str, Any]) -> dict[str, str]:
    out = {}
    for suffix, key in ENV_FIELDS:
        value = _scalar(data, key)
        out[f"RELEASE_{suffix}"] = "" if value is None else str(value)
    loader = _loader()
    out["RELEASE_PENDING"] = ",".join(data["pending"])
    out["RELEASE_RELEASES_URL"] = loader.releases_url(data)
    return out


def _ts_value(value: Any) -> str:
    if value is None:
        return "null"
    return json.dumps(value)


def _ts_lines(value: Any, key: str, indent: int) -> list[str]:
    pad = " " * indent
    if isinstance(value, dict):
        lines = [f"{pad}{key}: {{"]
        for sub, sub_value in value.items():
            lines += _ts_lines(sub_value, sub, indent + 2)
        lines.append(f"{pad}}},")
        return lines
    if isinstance(value, list):
        inline = f"{pad}{key}: [{', '.join(_ts_value(v) for v in value)}],"
        if len(inline) <= 80:
            return [inline]
        lines = [f"{pad}{key}: ["]
        for item in value:
            lines.append(f"{pad}  {_ts_value(item)},")
        lines.append(f"{pad}],")
        return lines
    return [f"{pad}{key}: {_ts_value(value)},"]


def render_ts(data: dict[str, Any]) -> str:
    """Render the committed console module in prettier's own style."""
    lines = [TS_HEADER.rstrip("\n"), "export const RELEASE_CHANNEL = {"]
    for key, value in data.items():
        lines += _ts_lines(value, key, 2)
    lines.append("} as const;")
    return "\n".join(lines) + TS_FOOTER


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    form = parser.add_mutually_exclusive_group(required=True)
    form.add_argument("--print", action="store_true")
    form.add_argument("--sh", action="store_true")
    form.add_argument("--gh-env", action="store_true")
    form.add_argument("--write-ts", action="store_true")
    parser.add_argument(
        "--out", type=Path, default=GENERATED_TS, help="--write-ts target"
    )
    parser.add_argument("--fact-source", type=Path, default=FACT_SOURCE)
    args = parser.parse_args(argv)

    data = _loader().load(args.fact_source)

    if args.print:
        print(json.dumps(data, indent=2))
        return 0
    if args.sh:
        for name, value in env_map(data).items():
            print(f"export {name}={value}")
        return 0
    if args.gh_env:
        target = os.environ.get("GITHUB_ENV")
        if not target:
            print("ERROR: --gh-env needs GITHUB_ENV to point at a file")
            return 1
        with open(target, "a", encoding="utf-8") as handle:
            for name, value in env_map(data).items():
                handle.write(f"{name}={value}\n")
        return 0
    rendered = render_ts(data)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
